os:
- linux
services:
- docker
language: node_js
node_js:
- 6.10.3
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"
env:
  global:
  - NODE_VERSION=6.10.3
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - HEROKU_API_KEY="eccfc73b-b203-4172-a54a-c25727202737"
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
after_success:
- heroku plugins:install heroku-cli-deploy
- heroku deploy:jar --jar target/*.war --app school-net
script:
- chmod +x mvnw
- "./mvnw clean"
- "./mvnw package -Pprod -DskipTests"
notifications:
  email:
  - myndykmykola@gmail.com

