os:
- linux
services:
- docker
language: node_js
node_js:
- 6.10.3
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: rBMAtwbeDv4fBkGmgvPDuLAfibWxHluCZzuD9ksbI6FZSPr6QTBSbTeYg23Ix1126H9XUBT+IJEijT/MDcs9zxY5G4J8lXjbmL5Kmj0CttcrTzfEGpYi1ifZK5btwnkW7dlBnZclcXeOocXJQwaeTTN3qfS88pQLMwNHS/LbCFvVyoLJa32LfQmMNHWtPpFgjOiDLHh9/VGENlZAqNRteSZj0BhBU6nNCk1nRoFMZQ3I6Fx2pUgN2jFPfINcMmFlxgAKCuPgLFju245JstyJmqLFEstdj8aDvSpuliAY48kerbVg6x4lgRHeQR5W009iDGEo4Bdk7nJYNpU/UD+2zUCKFI9uhoGbXHVqn6n+jcUR0Xm//yFy4yy8Q5Q94VMhael0fuD3+g00dFGRfDv4/p9NOW4LhGc7OoK2H5YywEVnvc+UfTVtUDQpbaXUmdZT6e20KYlzYSY6E/QPtrgj84T1ZIYEX5Xs9e1ErjRljcaLSdw2g3a0iMcSIllarAflAW/SCGRX8S/XcM/Oz911V9r5XE+cp+jiANbJAiNhDtTOaE3rxXK55C+bGsoZ5+KBcp3e2ICJxHXGHLV52i/9BaqA5AqyjYLmEecO+J+PZFXeyrWycjvNTZL93eQ6deVrb1qdJ2nX+zAW3PivtyFNJwvjhv+MdKvjzX0JcKd4gsc=
  on: travis-setupy
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"
env:
  global:
  - NODE_VERSION=6.10.3
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - PHANTOMJS_BIN=./node_modules/.bin/phantomjs
  - process.env.PHANTOMJS_BIN = './node_modules/.bin/phantomjs'
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install
script:
- chmod +x mvnw
- "./mvnw clean test"
- yarn test
- "./mvnw package -Pprod -DskipTests"
notifications:
  email: false
